---
title: "corpus_stats"
output: html_document
date: "2022-09-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(PerformanceAnalytics)
library(tibble)
library(tidyr)
```

```{r}
data <- read.csv('processed_data/language_endangerment_v2.csv')
```

```{r}
colnames(data)
```


```{r}
# create a new column that is the ratio # of noun concepts: # of adj concepts
data["noun_adj_concept_ratio"] = data["num_unique_noun_concepts"] / data["num_unique_adj_concepts" ]

# same but for words instead of concepts
data["noun_adj_word_ratio"] = data["num_unique_noun_words"] / data["num_unique_adj_words" ]

# word length ratio
data["noun_adj_word_len_ratio"] = data["mean_noun_word_len"] / data["mean_adj_word_len" ]

# get rid of Inf values
data <- data[data["noun_adj_concept_ratio"] != 'Inf', ]
data <- data[data["noun_adj_word_ratio"] != 'Inf', ]
data <- data[data["noun_adj_word_len_ratio"] != 'Inf', ]
data <- data[data['L1_pop'] > 0, ]
data <- data[data['GDPpc'] > 0, ]
data["noun_adj_concept_ratio"]
```
```{r}
ggplot(data, aes(noun_adj_word_ratio)) +
  geom_histogram(bins=20)

```


```{r}
# recode as 0 and 1
adj_noun_idx <- data['adj_noun_order_coded'] == 1
no_pref_idx <- data['adj_noun_order_coded'] == 2
noun_adj_idx <- data['adj_noun_order_coded'] == 3

data1 <- data
data1['adj_noun_order_coded'][no_pref_idx] = 0
data1['adj_noun_order_coded'][noun_adj_idx] = 0
data1['adj_noun_order_coded']
```

```{r}
# do the same coding for OV order
OV_no_pref_idx <- data['OV_order_coded'] == 3
OV_verb_first_index <- data['OV_order_coded'] == 2

# so OV is coded as 1 and everything else is coded as 0
data1['OV_order_coded'][OV_no_pref_idx] = 0
data1['OV_order_coded'][OV_verb_first_index] = 0
```


```{r}
# create a new predictor variable for total size of concept space/lexicon
data1['num_unique_concepts'] <- data1['num_unique_noun_concepts'] + data1['num_unique_adj_concepts']
data1['num_unique_words'] <- data1['num_unique_noun_words'] + data1['num_unique_adj_words']

# log transform corpus data
data1['log_noun_adj_word_ratio'] <- log(data1['noun_adj_word_ratio'])
data1['log_noun_adj_word_len_ratio'] <- log(data1['noun_adj_word_len_ratio'])
data1['log_num_unique_words'] <- log(data1['num_unique_words'])

data1['log_L1_pop'] <- log(data1['L1_pop'])
data1['log_GDPpc'] <- log(data1['GDPpc'])
data1['log_life_expectancy_60'] <- log(data1['life_expectancy_60'])

# scale the data for the regression
data1['log_L1_pop'] <- scale(data1['log_L1_pop'])
data1['log_GDPpc'] <- scale(data1['log_GDPpc'])
data1['log_life_expectancy_60'] <- scale(data1['log_life_expectancy_60'])

data1['GDPpc'] <- scale(data1['GDPpc'])
data1['life_expectancy_60'] <- scale(data1['life_expectancy_60'])
data1['education_spending'] <- scale(data1['education_spending'])

data1['num_unique_words'] <- scale(data1['num_unique_words'])

data1['log_noun_adj_word_ratio'] <- scale(data1['log_noun_adj_word_ratio'])
data1['log_noun_adj_word_len_ratio'] <- scale(data1['log_noun_adj_word_len_ratio'])


data1['noun_adj_word_ratio'] <- scale(data1['noun_adj_word_ratio'])
data1['noun_adj_word_len_ratio'] <- scale(data1['noun_adj_word_len_ratio'])
data1['log_num_unique_words'] <- scale(data1['log_num_unique_words'])

ggplot(data1, aes(log_life_expectancy_60)) +
  geom_histogram(bins=100)
```
```{r}
lmod <- glm(adj_noun_order_coded ~ 
                log_L1_pop + log_GDPpc + noun_adj_word_ratio + log_num_unique_words,
            data1, 
            #control = glmerControl(optimizer="bobyqa"),
            family='binomial')
summary(lmod)
```


```{r}
# make the language categorical so that we can have it as a random effect
data1['language'] <- unclass(data1['ISO'])

# same thing for language family
data1['language_family'] <- unclass(data1['family_x'])

lmod <- glmer(adj_noun_order_coded ~ OV_order_coded + 
                log_L1_pop + log_GDPpc + noun_adj_word_ratio + 
                log_num_unique_words + noun_adj_word_len_ratio + 
                (1|language_family), 
            data1, 
            control = glmerControl(optimizer="bobyqa"),
            family='binomial')
summary(lmod)
```
```{r}
data1['language_family']
ggplot(data=data1, aes(x = fct_infreq(language_family))) + geom_bar() + theme(axis.text.x = element_text(angle = 90))
```


```{r}
data2 <- data[data['description'] != 'Adjective-Noun', ]
no_pref_idx <- data2['description'] == 'No dominant order'
noun_adj_idx <- data2['description'] == 'Noun-Adjective'
data2['value'][no_pref_idx] = 1
data2['value'][noun_adj_idx] = 0
data2['value']
```
```{r}
lmod <- glm(value ~ GDPpc + life_expectancy_60 + education_spending + noun_adj_concept_ratio, data2, family='binomial')
summary(lmod)

lmod <- glm(value ~ L1_pop + GDPpc + life_expectancy_60 + education_spending + noun_adj_concept_ratio, data2, family='binomial')
summary(lmod)
```

```{r}
colnames(data1)
```

```{r}
ggplot(data=data, aes(x = adj_noun_order, y = noun_adj_word_ratio)) +
  geom_violin() +
  stat_summary(fun = "mean",
               geom = "crossbar", 
               width = 0.5,
               colour = "red")
```


```{r}
ggplot(data=data, aes(x = adj_noun_order, y = noun_adj_word_len_ratio)) +
  geom_violin() +
  stat_summary(fun = "mean",
               geom = "crossbar", 
               width = 0.5,
               colour = "red")
```


```{r}
ggplot(data = data, aes(x = reorder(ISO, noun_adj_word_len_ratio), y = noun_adj_word_len_ratio, fill = adj_noun_order)) + geom_bar(stat = "identity") + theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
```

```{r}
ggplot(data = data, aes(x = reorder(ISO, noun_adj_word_ratio), y = noun_adj_word_ratio, fill = adj_noun_order)) + geom_bar(stat = "identity") + theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
```

```{r fig.height=20, fig.width=12}
data1 %>%
filter(language_family > 2) %>%
ggplot(aes(x=OV_order, y=num_unique_words)) +
geom_histogram(stat='summary', fun=mean) +
facet_wrap(~language_family) +
  theme(strip.text.x = element_text(size = 20),
        axis.text = element_text(size = 16),
        axis.text.x = element_text(angle = 90))
```

